### PR TITLE
Use naersk for buildRustPackage

### PR DESCRIPTION
**Pull request by jD91mZM2**
It's way better than nixpkgs' rust facilities, because it will read your
lock file for hashes instead of relying on cargoSha256. Also, for me the
cargoSha256 hash is different in the CI which is a big problem.

Not sure how to add dependencies properly - I'm new to flox.

You can test it by using `channels.jD91mZM2.master.buildRustPackage`.
It's almost identical - although it won't include the .flox.json file
because `source.infoJson` seemed unavailable for me.

### CODE REVIEW

**Comment by bpiv400** [comment]
Thanks for the suggestion, @jD91mZM2. 

We don't want to replace `buildRustPackage` in flox because we want it to match the builder provided by the Nix community in Nixpkgs. 

But we think it's a great idea to add this as an additional builder! We're going to discuss internally with @Infinisil  and @grahamc  before going forward.

**Comment by Infinisil** [comment]
I guess a naersk builder could be declared under the `flox.naersk.buildRustPackage` attribute instead. In case nixpkgs gets a `pkgs.naersk` package, this would keep up the nixpkgs symmetry.

**Comment by grahamc** [comment]
From a namespacing perspective: :+1: on moving this to a `naersk` attribute namespace.

From a "should this merge?" question, we should consider the fact that it uses import from derivation, and make a policy decision at the repository level:

> import-from-derivation (IFD) is when you evaluate nix from a derivation result, for example `import (pkgs.writeText "n" "1 + 1")` will evaluate to 2. This is sometimes problematic because it requires evaluating some, building some, and then evaluating the build result. It has been described as "such a nice footgun.

Specifically, fetching the source (the derivation) then running callPackage (importing) on the result. Since this is doing a fetch of static files, as opposed to doing shadier code generation which is then imported ... maybe it isn't so bad. However, there are down sides: evaluating for a system which the local machine has no support for will fail, because it cannot perform the necessary build (`fetchFromGitHub`) to complete evaluation.

Nix itself could be improved to handle these cases better, but that is a "tomorrow" project.

**Comment by jD91mZM2** [comment]
I definitely understand avoiding evaluating after building, but I feel like there needs to be a way to have dependencies in your nix code.

Could flox adapt a flakes-like system where there's an `inputs` attribute containing links w/ hashes that are to be fetched and supplied? That way you could greatly limit what the user is able to do with the inputs - no shady code generation, just static fetching.

**Comment by grahamc** [comment]
I talked to @limeytexan today and the general consensus is that since this is a nearly trivial amount of IFD that it'll be okay. To merge, can you:

 - [ ] change the name like requested to use the naersk namespace
 - [ ] write corresponding documentation here: https://github.com/flox/nixexprs/blob/staging/docs/builders.md#floxbuildrustpackage ? Follow the pattern and style of documentation that is in place to the extent possible.

**Comment by jD91mZM2** [comment]
Not sure on how to add a namespace, but I think this works? I tried it quickly in my own nixexprs repository, and that seemed to work

**Comment by grahamc** [comment]
Looking good so far! The docs for Naersk are fantastic. Thank you for the update. Two more requests, which I regret forgetting about in my comment yesterday: can you add a test to the `tests` directory, and format *your changes* with `nixfmt`? _The remainder of this repository is not yet standardized in nixfmt, but I will be sending a PR with that shortly._

**Comment by jD91mZM2** [comment]
Let's hope this works. Is there a way for me to run tests in this repository locally?

**Review by grahamc — APPROVED** [review]
Thank you a lot for sticking with me through the multiple requests, it looks good!

**Comment by grahamc** [comment]
By the way, new PRs will come with instructions on how to run checks locally: https://raw.githubusercontent.com/flox/nixexprs/staging/.github/PULL_REQUEST_TEMPLATE.md

**Pull request merged**
